// Müşteri tarafındaki (PublicMenu.tsx ve altındaki her şey) sabit arayüz
// metinlerinin statik çeviri sözlüğü. item_translations/category_translations'tan
// farklı olarak bunlar kafeye özel DB içeriği DEĞİL — tüm kafelerde aynı, kodla
// birlikte paketlenen sabit ifadeler; bu yüzden çalışma zamanında AI çağrısı
// gerekmiyor, işletmeci hiçbir şey yapmıyor. PrintMenu.tsx ve TableRedirect.tsx
// kapsam dışı (bkz. plan notu).
//
// Kullanım: useT() (LocaleContext.tsx) ile `t('key')` çağrılır; seçili dilde
// çeviri yoksa Türkçe'ye düşer. `{n}`/`{password}` gibi yer tutucular basit
// string.replaceAll ile doldurulur.

import type { LocaleKey } from './locales'

export type UILang = 'tr' | LocaleKey

export const UI_TEXT = {
  'notFound.title': {
    tr: 'Menü bulunamadı',
    en: 'Menu not found',
    de: 'Menü nicht gefunden',
    ru: 'Меню не найдено',
    ar: 'القائمة غير موجودة',
    fr: 'Menu introuvable',
    fa: 'منو یافت نشد',
    uk: 'Меню не знайдено',
    es: 'Menú no encontrado',
    it: 'Menu non trovato',
    zh: '未找到菜单',
  },
  'notFound.body': {
    tr: 'Adres yanlış yazılmış olabilir. QR kodu yeniden okutmayı deneyin.',
    en: 'The address may be incorrect. Try scanning the QR code again.',
    de: 'Die Adresse ist möglicherweise falsch. Scannen Sie den QR-Code erneut.',
    ru: 'Возможно, адрес указан неверно. Попробуйте отсканировать QR-код заново.',
    ar: 'قد يكون العنوان غير صحيح. حاول مسح رمز QR مرة أخرى.',
    fr: "L'adresse est peut-être incorrecte. Essayez de scanner à nouveau le QR code.",
    fa: 'ممکن است آدرس اشتباه باشد. دوباره کد QR را اسکن کنید.',
    uk: 'Можливо, адресу вказано неправильно. Спробуйте відсканувати QR-код знову.',
    es: 'La dirección puede ser incorrecta. Intenta escanear el código QR de nuevo.',
    it: "L'indirizzo potrebbe essere errato. Prova a scansionare di nuovo il codice QR.",
    zh: '地址可能有误，请重新扫描二维码。',
  },
  'nav.all': {
    tr: 'Tümü',
    en: 'All',
    de: 'Alle',
    ru: 'Все',
    ar: 'الكل',
    fr: 'Tout',
    fa: 'همه',
    uk: 'Усі',
    es: 'Todo',
    it: 'Tutti',
    zh: '全部',
  },
  'nav.menuEyebrow': {
    tr: 'Menü',
    en: 'Menu',
    de: 'Menü',
    ru: 'Меню',
    ar: 'القائمة',
    fr: 'Menu',
    fa: 'منو',
    uk: 'Меню',
    es: 'Menú',
    it: 'Menu',
    zh: '菜单',
  },
  'nav.noResults': {
    tr: 'Bu filtrelere uyan ürün kalmadı. Filtreyi gevşetmeyi deneyin.',
    en: 'No items match these filters. Try loosening the filter.',
    de: 'Keine Artikel entsprechen diesen Filtern. Versuchen Sie, den Filter zu lockern.',
    ru: 'Нет блюд, соответствующих этим фильтрам. Попробуйте ослабить фильтр.',
    ar: 'لا توجد عناصر تطابق هذه الفلاتر. حاول تخفيف الفلتر.',
    fr: 'Aucun article ne correspond à ces filtres. Essayez de réduire le filtre.',
    fa: 'موردی مطابق این فیلترها یافت نشد. فیلتر را کمتر کنید.',
    uk: 'Немає страв, що відповідають цим фільтрам. Спробуйте послабити фільтр.',
    es: 'Ningún producto coincide con estos filtros. Intenta reducir el filtro.',
    it: 'Nessun articolo corrisponde a questi filtri. Prova ad allentare il filtro.',
    zh: '没有符合这些筛选条件的菜品，请尝试放宽筛选。',
  },
  'badge.kcal': {
    tr: '{n} kcal',
    en: '{n} kcal',
    de: '{n} kcal',
    ru: '{n} ккал',
    ar: '{n} سعرة حرارية',
    fr: '{n} kcal',
    fa: '{n} کالری',
    uk: '{n} ккал',
    es: '{n} kcal',
    it: '{n} kcal',
    zh: '{n} 千卡',
  },
  'badge.alcohol': {
    tr: 'Alkollü',
    en: 'Contains alcohol',
    de: 'Enthält Alkohol',
    ru: 'Содержит алкоголь',
    ar: 'يحتوي على كحول',
    fr: "Contient de l'alcool",
    fa: 'حاوی الکل',
    uk: 'Містить алкоголь',
    es: 'Contiene alcohol',
    it: 'Contiene alcol',
    zh: '含酒精',
  },
  'badge.pork': {
    tr: 'Domuz ürünü',
    en: 'Contains pork',
    de: 'Enthält Schweinefleisch',
    ru: 'Содержит свинину',
    ar: 'يحتوي على لحم الخنزير',
    fr: 'Contient du porc',
    fa: 'حاوی گوشت خوک',
    uk: 'Містить свинину',
    es: 'Contiene cerdo',
    it: 'Contiene maiale',
    zh: '含猪肉',
  },
  'allergen.filterLabel': {
    tr: 'Alerjen filtresi',
    en: 'Allergen filter',
    de: 'Allergenfilter',
    ru: 'Фильтр аллергенов',
    ar: 'فلتر مسببات الحساسية',
    fr: 'Filtre allergènes',
    fa: 'فیلتر آلرژن',
    uk: 'Фільтр алергенів',
    es: 'Filtro de alérgenos',
    it: 'Filtro allergeni',
    zh: '过敏原筛选',
  },
  'allergen.filterExcluded': {
    tr: '{n} hariç',
    en: '{n} excluded',
    de: '{n} ausgeschlossen',
    ru: '{n} исключено',
    ar: 'استبعاد {n}',
    fr: '{n} exclu(s)',
    fa: '{n} حذف‌شده',
    uk: '{n} виключено',
    es: '{n} excluidos',
    it: '{n} esclusi',
    zh: '已排除 {n} 项',
  },
  'allergen.filterHelp': {
    tr: 'İçermesini istemediğiniz alerjenleri seçin; o ürünler listeden çıkar.',
    en: 'Select the allergens you want to avoid; matching items will be hidden.',
    de: 'Wählen Sie Allergene, die Sie vermeiden möchten; passende Artikel werden ausgeblendet.',
    ru: 'Выберите аллергены, которых хотите избежать — такие блюда будут скрыты.',
    ar: 'اختر مسببات الحساسية التي تريد تجنبها؛ سيتم إخفاء العناصر المطابقة.',
    fr: 'Sélectionnez les allergènes à éviter ; les articles correspondants seront masqués.',
    fa: 'آلرژن‌هایی که می‌خواهید نداشته باشد را انتخاب کنید؛ آن موارد پنهان می‌شوند.',
    uk: 'Виберіть алергени, яких хочете уникнути — такі страви буде приховано.',
    es: 'Selecciona los alérgenos que quieres evitar; esos productos se ocultarán.',
    it: 'Seleziona gli allergeni da evitare; gli articoli corrispondenti verranno nascosti.',
    zh: '选择您想避免的过敏原，含有这些成分的菜品将被隐藏。',
  },
  'allergen.legendTitle': {
    tr: 'Alerjen bilgilendirmesi',
    en: 'Allergen information',
    de: 'Allergeninformationen',
    ru: 'Информация об аллергенах',
    ar: 'معلومات مسببات الحساسية',
    fr: 'Informations sur les allergènes',
    fa: 'اطلاعات آلرژن‌ها',
    uk: 'Інформація про алергени',
    es: 'Información sobre alérgenos',
    it: 'Informazioni sugli allergeni',
    zh: '过敏原信息',
  },
  'allergen.legendBody': {
    tr: 'Alerjen, enerji (kcal), alkol ve domuz ürünü bilgileri Türk Gıda Kodeksi Gıda Etiketleme ve Tüketicileri Bilgilendirme Yönetmeliği kapsamında beyan edilmiştir. Şiddetli alerjiniz varsa siparişten önce personelimize danışın.',
    en: 'Allergen, energy (kcal), alcohol and pork content are declared under Turkish Food Codex labeling regulations. If you have a severe allergy, please ask our staff before ordering.',
    de: 'Allergen-, Energie- (kcal), Alkohol- und Schweinefleischangaben erfolgen gemäß der türkischen Lebensmittelkennzeichnungsverordnung. Bei einer schweren Allergie wenden Sie sich bitte vor der Bestellung an unser Personal.',
    ru: 'Информация об аллергенах, энергетической ценности (ккал), алкоголе и свинине указана в соответствии с турецким регламентом маркировки пищевых продуктов. При тяжёлой аллергии, пожалуйста, уточните у персонала перед заказом.',
    ar: 'يتم الإفصاح عن مسببات الحساسية والطاقة (كالوري) والكحول ولحم الخنزير وفقاً للائحة التركية لوسم الأغذية. إذا كانت لديك حساسية شديدة، يرجى استشارة موظفينا قبل الطلب.',
    fr: "Les allergènes, l'apport énergétique (kcal), l'alcool et le porc sont déclarés conformément à la réglementation turque sur l'étiquetage alimentaire. En cas d'allergie sévère, merci de consulter notre personnel avant de commander.",
    fa: 'اطلاعات آلرژن، انرژی (کالری)، الکل و گوشت خوک طبق مقررات برچسب‌گذاری مواد غذایی ترکیه اعلام شده است. در صورت حساسیت شدید، لطفاً پیش از سفارش با پرسنل ما مشورت کنید.',
    uk: 'Інформацію про алергени, енергетичну цінність (ккал), алкоголь і свинину надано відповідно до турецького регламенту маркування харчових продуктів. У разі тяжкої алергії, будь ласка, зверніться до персоналу перед замовленням.',
    es: 'La información sobre alérgenos, energía (kcal), alcohol y cerdo se declara conforme a la normativa turca de etiquetado alimentario. Si tienes una alergia grave, consulta con nuestro personal antes de pedir.',
    it: "Le informazioni su allergeni, energia (kcal), alcol e maiale sono dichiarate secondo la normativa turca sull'etichettatura alimentare. In caso di allergia grave, ti preghiamo di parlare con il nostro staff prima di ordinare.",
    zh: '过敏原、能量（千卡）、酒精及猪肉成分信息均依照土耳其食品标签法规标示。如有严重过敏，请在点餐前告知我们的工作人员。',
  },
  'allergen.phone': {
    tr: 'Tel',
    en: 'Phone',
    de: 'Tel.',
    ru: 'Тел.',
    ar: 'هاتف',
    fr: 'Tél.',
    fa: 'تلفن',
    uk: 'Тел.',
    es: 'Tel.',
    it: 'Tel.',
    zh: '电话',
  },
  'itemDetail.allergensTitle': {
    tr: 'Alerjenler',
    en: 'Allergens',
    de: 'Allergene',
    ru: 'Аллергены',
    ar: 'مسببات الحساسية',
    fr: 'Allergènes',
    fa: 'آلرژن‌ها',
    uk: 'Алергени',
    es: 'Alérgenos',
    it: 'Allergeni',
    zh: '过敏原',
  },
  'itemDetail.close': {
    tr: 'Kapat',
    en: 'Close',
    de: 'Schließen',
    ru: 'Закрыть',
    ar: 'إغلاق',
    fr: 'Fermer',
    fa: 'بستن',
    uk: 'Закрити',
    es: 'Cerrar',
    it: 'Chiudi',
    zh: '关闭',
  },
  'itemDetail.addToCart': {
    tr: 'Sepete Ekle',
    en: 'Add to Cart',
    de: 'In den Warenkorb',
    ru: 'Добавить в корзину',
    ar: 'أضف إلى السلة',
    fr: 'Ajouter au panier',
    fa: 'افزودن به سبد',
    uk: 'Додати в кошик',
    es: 'Añadir al carrito',
    it: 'Aggiungi al carrello',
    zh: '加入购物车',
  },
  'itemDetail.added': {
    tr: 'Sepete eklendi',
    en: 'Added to cart',
    de: 'Zum Warenkorb hinzugefügt',
    ru: 'Добавлено в корзину',
    ar: 'أُضيف إلى السلة',
    fr: 'Ajouté au panier',
    fa: 'به سبد افزوده شد',
    uk: 'Додано в кошик',
    es: 'Añadido al carrito',
    it: 'Aggiunto al carrello',
    zh: '已加入购物车',
  },
  'itemDetail.noteLabel': {
    tr: 'Özel istek (opsiyonel)',
    en: 'Special request (optional)',
    de: 'Sonderwunsch (optional)',
    ru: 'Особые пожелания (необязательно)',
    ar: 'طلب خاص (اختياري)',
    fr: 'Demande spéciale (facultatif)',
    fa: 'درخواست ویژه (اختیاری)',
    uk: 'Особливі побажання (необов’язково)',
    es: 'Petición especial (opcional)',
    it: 'Richiesta speciale (opzionale)',
    zh: '特殊要求（可选）',
  },
  'itemDetail.notePlaceholder': {
    tr: 'örn. soğansız, az pişmiş',
    en: 'e.g. no onion, well done',
    de: 'z. B. ohne Zwiebeln, gut durch',
    ru: 'напр. без лука',
    ar: 'مثال: بدون بصل',
    fr: 'ex. sans oignon',
    fa: 'مثلاً بدون پیاز',
    uk: 'напр. без цибулі',
    es: 'ej. sin cebolla',
    it: 'es. senza cipolla',
    zh: '例如：不要洋葱',
  },
  'waiter.callButton': {
    tr: 'Garson Çağır',
    en: 'Call Waiter',
    de: 'Kellner rufen',
    ru: 'Позвать официанта',
    ar: 'استدعاء النادل',
    fr: 'Appeler le serveur',
    fa: 'صدا زدن گارسون',
    uk: 'Покликати офіціанта',
    es: 'Llamar al camarero',
    it: 'Chiama il cameriere',
    zh: '呼叫服务员',
  },
  'waiter.calling': {
    tr: 'Çağrılıyor…',
    en: 'Calling…',
    de: 'Wird gerufen…',
    ru: 'Вызываем…',
    ar: 'جارٍ الاستدعاء…',
    fr: 'Appel en cours…',
    fa: 'در حال صدا زدن…',
    uk: 'Викликаємо…',
    es: 'Llamando…',
    it: 'Chiamata in corso…',
    zh: '正在呼叫…',
  },
  'waiter.pending': {
    tr: 'Çağrınız iletildi',
    en: 'Your call has been sent',
    de: 'Ihr Ruf wurde gesendet',
    ru: 'Ваш вызов отправлен',
    ar: 'تم إرسال طلبك',
    fr: 'Votre appel a été envoyé',
    fa: 'درخواست شما ارسال شد',
    uk: 'Ваш виклик надіслано',
    es: 'Tu llamada ha sido enviada',
    it: 'La tua chiamata è stata inviata',
    zh: '您的呼叫已发送',
  },
  'waiter.acknowledged': {
    tr: 'Personel geliyor',
    en: 'Staff is on the way',
    de: 'Personal ist unterwegs',
    ru: 'Персонал уже идёт',
    ar: 'الموظف في الطريق',
    fr: 'Le personnel arrive',
    fa: 'پرسنل در راه است',
    uk: 'Персонал вже йде',
    es: 'El personal está en camino',
    it: 'Il personale sta arrivando',
    zh: '工作人员正在赶来',
  },
  'waiter.expired': {
    tr: 'Garson çağırmak için QR kodu tekrar okutun',
    en: 'Scan the QR code again to call a waiter',
    de: 'Scannen Sie den QR-Code erneut, um einen Kellner zu rufen',
    ru: 'Отсканируйте QR-код заново, чтобы позвать официанта',
    ar: 'امسح رمز QR مرة أخرى لاستدعاء النادل',
    fr: 'Scannez à nouveau le QR code pour appeler un serveur',
    fa: 'برای صدا زدن گارسون دوباره کد QR را اسکن کنید',
    uk: 'Відскануйте QR-код знову, щоб покликати офіціанта',
    es: 'Escanea el código QR de nuevo para llamar a un camarero',
    it: 'Scansiona di nuovo il codice QR per chiamare un cameriere',
    zh: '请重新扫描二维码以呼叫服务员',
  },
  'reservation.makeButton': {
    tr: 'Rezervasyon Yap',
    en: 'Make a Reservation',
    de: 'Reservierung vornehmen',
    ru: 'Забронировать',
    ar: 'إجراء حجز',
    fr: 'Faire une réservation',
    fa: 'رزرو کنید',
    uk: 'Забронювати',
    es: 'Hacer una reserva',
    it: 'Prenota',
    zh: '预订',
  },
  'reservation.myReservations': {
    tr: 'Rezervasyonlarım',
    en: 'My Reservations',
    de: 'Meine Reservierungen',
    ru: 'Мои брони',
    ar: 'حجوزاتي',
    fr: 'Mes réservations',
    fa: 'رزروهای من',
    uk: 'Мої бронювання',
    es: 'Mis reservas',
    it: 'Le mie prenotazioni',
    zh: '我的预订',
  },
  'reservation.title': {
    tr: 'Rezervasyon',
    en: 'Reservation',
    de: 'Reservierung',
    ru: 'Бронирование',
    ar: 'الحجز',
    fr: 'Réservation',
    fa: 'رزرو',
    uk: 'Бронювання',
    es: 'Reserva',
    it: 'Prenotazione',
    zh: '预订',
  },
  'reservation.newButton': {
    tr: 'Yeni Rezervasyon Yap',
    en: 'Make a New Reservation',
    de: 'Neue Reservierung vornehmen',
    ru: 'Новая бронь',
    ar: 'إجراء حجز جديد',
    fr: 'Faire une nouvelle réservation',
    fa: 'رزرو جدید',
    uk: 'Нове бронювання',
    es: 'Hacer una nueva reserva',
    it: 'Fai una nuova prenotazione',
    zh: '新建预订',
  },
  'reservation.nameLabel': {
    tr: 'Ad Soyad',
    en: 'Full Name',
    de: 'Name',
    ru: 'Имя и фамилия',
    ar: 'الاسم الكامل',
    fr: 'Nom complet',
    fa: 'نام و نام‌خانوادگی',
    uk: "Ім'я та прізвище",
    es: 'Nombre completo',
    it: 'Nome e cognome',
    zh: '姓名',
  },
  'reservation.phoneLabel': {
    tr: 'Telefon',
    en: 'Phone',
    de: 'Telefon',
    ru: 'Телефон',
    ar: 'الهاتف',
    fr: 'Téléphone',
    fa: 'تلفن',
    uk: 'Телефон',
    es: 'Teléfono',
    it: 'Telefono',
    zh: '电话',
  },
  'reservation.dateLabel': {
    tr: 'Tarih',
    en: 'Date',
    de: 'Datum',
    ru: 'Дата',
    ar: 'التاريخ',
    fr: 'Date',
    fa: 'تاریخ',
    uk: 'Дата',
    es: 'Fecha',
    it: 'Data',
    zh: '日期',
  },
  'reservation.timeLabel': {
    tr: 'Saat',
    en: 'Time',
    de: 'Uhrzeit',
    ru: 'Время',
    ar: 'الوقت',
    fr: 'Heure',
    fa: 'ساعت',
    uk: 'Час',
    es: 'Hora',
    it: 'Ora',
    zh: '时间',
  },
  'reservation.partySizeLabel': {
    tr: 'Kişi Sayısı',
    en: 'Party Size',
    de: 'Personenzahl',
    ru: 'Количество гостей',
    ar: 'عدد الأشخاص',
    fr: 'Nombre de personnes',
    fa: 'تعداد نفرات',
    uk: 'Кількість осіб',
    es: 'Número de personas',
    it: 'Numero di persone',
    zh: '人数',
  },
  'reservation.noteLabel': {
    tr: 'Not (opsiyonel)',
    en: 'Note (optional)',
    de: 'Notiz (optional)',
    ru: 'Комментарий (необязательно)',
    ar: 'ملاحظة (اختياري)',
    fr: 'Remarque (facultatif)',
    fa: 'یادداشت (اختیاری)',
    uk: 'Примітка (необовʼязково)',
    es: 'Nota (opcional)',
    it: 'Nota (facoltativa)',
    zh: '备注（可选）',
  },
  'reservation.submitButton': {
    tr: 'Rezervasyon Talebi Gönder',
    en: 'Send Reservation Request',
    de: 'Reservierungsanfrage senden',
    ru: 'Отправить запрос на бронь',
    ar: 'إرسال طلب الحجز',
    fr: 'Envoyer la demande de réservation',
    fa: 'ارسال درخواست رزرو',
    uk: 'Надіслати запит на бронювання',
    es: 'Enviar solicitud de reserva',
    it: 'Invia richiesta di prenotazione',
    zh: '发送预订请求',
  },
  'reservation.submitting': {
    tr: 'Gönderiliyor…',
    en: 'Sending…',
    de: 'Wird gesendet…',
    ru: 'Отправка…',
    ar: 'جارٍ الإرسال…',
    fr: 'Envoi en cours…',
    fa: 'در حال ارسال…',
    uk: 'Надсилання…',
    es: 'Enviando…',
    it: 'Invio in corso…',
    zh: '发送中…',
  },
  'reservation.backToList': {
    tr: 'Vazgeç, rezervasyonlarıma dön',
    en: 'Cancel, back to my reservations',
    de: 'Abbrechen, zurück zu meinen Reservierungen',
    ru: 'Отмена, вернуться к моим бронированиям',
    ar: 'إلغاء، العودة إلى حجوزاتي',
    fr: 'Annuler, retour à mes réservations',
    fa: 'انصراف، بازگشت به رزروهای من',
    uk: 'Скасувати, повернутися до моїх бронювань',
    es: 'Cancelar, volver a mis reservas',
    it: 'Annulla, torna alle mie prenotazioni',
    zh: '取消，返回我的预订',
  },
  'reservation.validationError': {
    tr: 'Lütfen tüm zorunlu alanları doldurun.',
    en: 'Please fill in all required fields.',
    de: 'Bitte füllen Sie alle Pflichtfelder aus.',
    ru: 'Пожалуйста, заполните все обязательные поля.',
    ar: 'يرجى ملء جميع الحقول المطلوبة.',
    fr: 'Veuillez remplir tous les champs obligatoires.',
    fa: 'لطفاً همه فیلدهای الزامی را پر کنید.',
    uk: "Будь ласка, заповніть усі обов'язкові поля.",
    es: 'Completa todos los campos obligatorios.',
    it: 'Compila tutti i campi obbligatori.',
    zh: '请填写所有必填项。',
  },
  'reservation.dateTimeError': {
    tr: 'Geçerli bir tarih/saat girin.',
    en: 'Please enter a valid date/time.',
    de: 'Bitte geben Sie ein gültiges Datum/eine gültige Uhrzeit ein.',
    ru: 'Введите корректную дату и время.',
    ar: 'يرجى إدخال تاريخ/وقت صحيح.',
    fr: 'Veuillez saisir une date/heure valide.',
    fa: 'یک تاریخ/ساعت معتبر وارد کنید.',
    uk: 'Введіть коректну дату/час.',
    es: 'Introduce una fecha/hora válida.',
    it: 'Inserisci una data/ora valida.',
    zh: '请输入有效的日期/时间。',
  },
  'reservation.submitError': {
    tr: 'Talep gönderilemedi, lütfen tekrar deneyin.',
    en: 'Could not send the request, please try again.',
    de: 'Anfrage konnte nicht gesendet werden, bitte versuchen Sie es erneut.',
    ru: 'Не удалось отправить запрос, попробуйте ещё раз.',
    ar: 'تعذر إرسال الطلب، يرجى المحاولة مرة أخرى.',
    fr: "Impossible d'envoyer la demande, veuillez réessayer.",
    fa: 'ارسال درخواست ناموفق بود، دوباره تلاش کنید.',
    uk: 'Не вдалося надіслати запит, спробуйте ще раз.',
    es: 'No se pudo enviar la solicitud, inténtalo de nuevo.',
    it: 'Impossibile inviare la richiesta, riprova.',
    zh: '请求发送失败，请重试。',
  },
  'reservation.statusPending': {
    tr: 'Bekliyor',
    en: 'Pending',
    de: 'Ausstehend',
    ru: 'Ожидание',
    ar: 'قيد الانتظار',
    fr: 'En attente',
    fa: 'در انتظار',
    uk: 'Очікує',
    es: 'Pendiente',
    it: 'In attesa',
    zh: '等待中',
  },
  'reservation.statusConfirmed': {
    tr: 'Onaylandı',
    en: 'Confirmed',
    de: 'Bestätigt',
    ru: 'Подтверждено',
    ar: 'مؤكد',
    fr: 'Confirmée',
    fa: 'تأیید شد',
    uk: 'Підтверджено',
    es: 'Confirmada',
    it: 'Confermata',
    zh: '已确认',
  },
  'reservation.statusRejected': {
    tr: 'Reddedildi',
    en: 'Declined',
    de: 'Abgelehnt',
    ru: 'Отклонено',
    ar: 'مرفوض',
    fr: 'Refusée',
    fa: 'رد شد',
    uk: 'Відхилено',
    es: 'Rechazada',
    it: 'Rifiutata',
    zh: '已拒绝',
  },
  'reservation.statusCancelled': {
    tr: 'İptal Edildi',
    en: 'Cancelled',
    de: 'Storniert',
    ru: 'Отменено',
    ar: 'ملغى',
    fr: 'Annulée',
    fa: 'لغو شد',
    uk: 'Скасовано',
    es: 'Cancelada',
    it: 'Annullata',
    zh: '已取消',
  },
  'reservation.pendingNote': {
    tr: 'İşletme onayladığında/reddettiğinde burada güncellenir.',
    en: 'This will update once the business confirms or declines.',
    de: 'Dies wird aktualisiert, sobald das Restaurant bestätigt oder ablehnt.',
    ru: 'Здесь появится обновление, когда заведение подтвердит или отклонит бронь.',
    ar: 'سيتم تحديث هذا عند موافقة أو رفض المطعم.',
    fr: "Ceci sera mis à jour lorsque l'établissement confirmera ou refusera.",
    fa: 'وقتی کسب‌وکار تأیید یا رد کند، اینجا به‌روزرسانی می‌شود.',
    uk: 'Тут з’явиться оновлення, коли заклад підтвердить або відхилить.',
    es: 'Esto se actualizará cuando el negocio confirme o rechace.',
    it: "Questo si aggiornerà quando l'attività confermerà o rifiuterà.",
    zh: '商家确认或拒绝后，此处将更新。',
  },
  'reservation.rejectedNote': {
    tr: 'Maalesef bu saat için yer bulunamadı. Farklı bir saat için tekrar deneyebilirsiniz.',
    en: 'Unfortunately no table is available at this time. You can try again for a different time.',
    de: 'Leider ist zu dieser Zeit kein Tisch verfügbar. Sie können es für eine andere Uhrzeit erneut versuchen.',
    ru: 'К сожалению, на это время нет свободных мест. Попробуйте выбрать другое время.',
    ar: 'للأسف لا توجد طاولة متاحة في هذا الوقت. يمكنك المحاولة مرة أخرى في وقت آخر.',
    fr: "Malheureusement, aucune table n'est disponible à cette heure. Vous pouvez réessayer à un autre horaire.",
    fa: 'متأسفانه در این ساعت جایی موجود نیست. برای ساعت دیگری دوباره امتحان کنید.',
    uk: 'На жаль, на цей час немає вільних місць. Спробуйте інший час.',
    es: 'Lo sentimos, no hay mesa disponible a esa hora. Puedes intentarlo con otro horario.',
    it: "Purtroppo non c'è un tavolo disponibile a quest'ora. Puoi riprovare con un altro orario.",
    zh: '很抱歉，该时段暂无空位，请尝试其他时间。',
  },
  'reservation.partySizeSuffix': {
    tr: '{n} kişi',
    en: '{n} guests',
    de: '{n} Personen',
    ru: '{n} чел.',
    ar: '{n} أشخاص',
    fr: '{n} personnes',
    fa: '{n} نفر',
    uk: '{n} осіб',
    es: '{n} personas',
    it: '{n} persone',
    zh: '{n} 位',
  },
  'order.orderButton': {
    tr: 'Sipariş Ver',
    en: 'Order',
    de: 'Bestellen',
    ru: 'Заказать',
    ar: 'اطلب الآن',
    fr: 'Commander',
    fa: 'سفارش دهید',
    uk: 'Замовити',
    es: 'Pedir',
    it: 'Ordina',
    zh: '下单',
  },
  'order.cartButton': {
    tr: 'Sepetim ({n})',
    en: 'My Cart ({n})',
    de: 'Warenkorb ({n})',
    ru: 'Корзина ({n})',
    ar: 'سلتي ({n})',
    fr: 'Mon panier ({n})',
    fa: 'سبد من ({n})',
    uk: 'Мій кошик ({n})',
    es: 'Mi carrito ({n})',
    it: 'Il mio carrello ({n})',
    zh: '购物车（{n}）',
  },
  'order.myOrders': {
    tr: 'Siparişlerim ({n})',
    en: 'My Orders ({n})',
    de: 'Meine Bestellungen ({n})',
    ru: 'Мои заказы ({n})',
    ar: 'طلباتي ({n})',
    fr: 'Mes commandes ({n})',
    fa: 'سفارش‌های من ({n})',
    uk: 'Мої замовлення ({n})',
    es: 'Mis pedidos ({n})',
    it: 'I miei ordini ({n})',
    zh: '我的订单（{n}）',
  },
  'order.cartTitle': {
    tr: 'Sepetim',
    en: 'My Cart',
    de: 'Warenkorb',
    ru: 'Корзина',
    ar: 'سلتي',
    fr: 'Mon panier',
    fa: 'سبد من',
    uk: 'Мій кошик',
    es: 'Mi carrito',
    it: 'Il mio carrello',
    zh: '购物车',
  },
  'order.myOrdersTitle': {
    tr: 'Siparişlerim',
    en: 'My Orders',
    de: 'Meine Bestellungen',
    ru: 'Мои заказы',
    ar: 'طلباتي',
    fr: 'Mes commandes',
    fa: 'سفارش‌های من',
    uk: 'Мої замовлення',
    es: 'Mis pedidos',
    it: 'I miei ordini',
    zh: '我的订单',
  },
  'order.emptyCart': {
    tr: 'Sepetiniz boş. Menüden bir ürünün üzerine dokunup "Sepete Ekle" ile ekleyin.',
    en: 'Your cart is empty. Tap an item in the menu and add it with "Add to Cart".',
    de: 'Ihr Warenkorb ist leer. Tippen Sie auf einen Artikel im Menü und fügen Sie ihn mit „In den Warenkorb" hinzu.',
    ru: 'Ваша корзина пуста. Нажмите на блюдо в меню и добавьте его кнопкой «Добавить в корзину».',
    ar: 'سلتك فارغة. اضغط على عنصر في القائمة وأضفه عبر "أضف إلى السلة".',
    fr: 'Votre panier est vide. Touchez un article du menu et ajoutez-le avec « Ajouter au panier ».',
    fa: 'سبد شما خالی است. روی یک مورد در منو بزنید و با «افزودن به سبد» اضافه کنید.',
    uk: 'Ваш кошик порожній. Торкніться страви в меню та додайте кнопкою «Додати в кошик».',
    es: 'Tu carrito está vacío. Toca un producto del menú y añádelo con "Añadir al carrito".',
    it: 'Il tuo carrello è vuoto. Tocca un articolo del menu e aggiungilo con "Aggiungi al carrello".',
    zh: '购物车是空的。请在菜单中点选菜品并点击"加入购物车"。',
  },
  'order.total': {
    tr: 'Toplam',
    en: 'Total',
    de: 'Gesamt',
    ru: 'Итого',
    ar: 'الإجمالي',
    fr: 'Total',
    fa: 'جمع کل',
    uk: 'Разом',
    es: 'Total',
    it: 'Totale',
    zh: '总计',
  },
  'order.submitButton': {
    tr: 'Siparişi Gönder',
    en: 'Place Order',
    de: 'Bestellung aufgeben',
    ru: 'Оформить заказ',
    ar: 'إرسال الطلب',
    fr: 'Passer la commande',
    fa: 'ثبت سفارش',
    uk: 'Оформити замовлення',
    es: 'Realizar pedido',
    it: "Invia l'ordine",
    zh: '提交订单',
  },
  'order.submitting': {
    tr: 'Gönderiliyor…',
    en: 'Sending…',
    de: 'Wird gesendet…',
    ru: 'Отправка…',
    ar: 'جارٍ الإرسال…',
    fr: 'Envoi en cours…',
    fa: 'در حال ارسال…',
    uk: 'Надсилання…',
    es: 'Enviando…',
    it: 'Invio in corso…',
    zh: '发送中…',
  },
  'order.newOrderButton': {
    tr: 'Yeni Sipariş Ver',
    en: 'Place a New Order',
    de: 'Neue Bestellung aufgeben',
    ru: 'Новый заказ',
    ar: 'إرسال طلب جديد',
    fr: 'Passer une nouvelle commande',
    fa: 'سفارش جدید',
    uk: 'Нове замовлення',
    es: 'Hacer un nuevo pedido',
    it: 'Fai un nuovo ordine',
    zh: '新建订单',
  },
  'order.backToOrders': {
    tr: 'Vazgeç, siparişlerime dön',
    en: 'Cancel, back to my orders',
    de: 'Abbrechen, zurück zu meinen Bestellungen',
    ru: 'Отмена, вернуться к моим заказам',
    ar: 'إلغاء، العودة إلى طلباتي',
    fr: 'Annuler, retour à mes commandes',
    fa: 'انصراف، بازگشت به سفارش‌های من',
    uk: 'Скасувати, повернутися до моїх замовлень',
    es: 'Cancelar, volver a mis pedidos',
    it: 'Annulla, torna ai miei ordini',
    zh: '取消，返回我的订单',
  },
  'order.validationError': {
    tr: 'Lütfen ad soyad ve telefon girin.',
    en: 'Please enter your name and phone number.',
    de: 'Bitte geben Sie Namen und Telefonnummer ein.',
    ru: 'Пожалуйста, укажите имя и телефон.',
    ar: 'يرجى إدخال الاسم ورقم الهاتف.',
    fr: 'Veuillez saisir votre nom et votre numéro de téléphone.',
    fa: 'لطفاً نام و شماره تلفن را وارد کنید.',
    uk: "Будь ласка, вкажіть ім'я та телефон.",
    es: 'Introduce tu nombre y teléfono.',
    it: 'Inserisci nome e numero di telefono.',
    zh: '请填写姓名和电话号码。',
  },
  'order.emptyCartError': {
    tr: 'Sepetiniz boş.',
    en: 'Your cart is empty.',
    de: 'Ihr Warenkorb ist leer.',
    ru: 'Ваша корзина пуста.',
    ar: 'سلتك فارغة.',
    fr: 'Votre panier est vide.',
    fa: 'سبد شما خالی است.',
    uk: 'Ваш кошик порожній.',
    es: 'Tu carrito está vacío.',
    it: 'Il tuo carrello è vuoto.',
    zh: '购物车是空的。',
  },
  'order.submitError': {
    tr: 'Sipariş gönderilemedi, lütfen tekrar deneyin.',
    en: 'Could not send the order, please try again.',
    de: 'Bestellung konnte nicht gesendet werden, bitte versuchen Sie es erneut.',
    ru: 'Не удалось отправить заказ, попробуйте ещё раз.',
    ar: 'تعذر إرسال الطلب، يرجى المحاولة مرة أخرى.',
    fr: "Impossible d'envoyer la commande, veuillez réessayer.",
    fa: 'ارسال سفارش ناموفق بود، دوباره تلاش کنید.',
    uk: 'Не вдалося надіслати замовлення, спробуйте ще раз.',
    es: 'No se pudo enviar el pedido, inténtalo de nuevo.',
    it: "Impossibile inviare l'ordine, riprova.",
    zh: '订单发送失败，请重试。',
  },
  'order.itemNote': {
    tr: 'Not: {note}',
    en: 'Note: {note}',
    de: 'Hinweis: {note}',
    ru: 'Примечание: {note}',
    ar: 'ملاحظة: {note}',
    fr: 'Note : {note}',
    fa: 'یادداشت: {note}',
    uk: 'Примітка: {note}',
    es: 'Nota: {note}',
    it: 'Nota: {note}',
    zh: '备注：{note}',
  },
  'order.statusPending': {
    tr: 'Bekliyor',
    en: 'Pending',
    de: 'Ausstehend',
    ru: 'Ожидание',
    ar: 'قيد الانتظار',
    fr: 'En attente',
    fa: 'در انتظار',
    uk: 'Очікує',
    es: 'Pendiente',
    it: 'In attesa',
    zh: '等待中',
  },
  'order.statusPreparing': {
    tr: 'Hazırlanıyor',
    en: 'Preparing',
    de: 'Wird zubereitet',
    ru: 'Готовится',
    ar: 'قيد التحضير',
    fr: 'En préparation',
    fa: 'در حال آماده‌سازی',
    uk: 'Готується',
    es: 'En preparación',
    it: 'In preparazione',
    zh: '制作中',
  },
  'order.statusReady': {
    tr: 'Hazır!',
    en: 'Ready!',
    de: 'Fertig!',
    ru: 'Готово!',
    ar: 'جاهز!',
    fr: 'Prêt !',
    fa: 'آماده است!',
    uk: 'Готово!',
    es: '¡Listo!',
    it: 'Pronto!',
    zh: '已完成！',
  },
  'order.statusCompleted': {
    tr: 'Tamamlandı',
    en: 'Completed',
    de: 'Abgeschlossen',
    ru: 'Завершено',
    ar: 'مكتمل',
    fr: 'Terminée',
    fa: 'تکمیل شد',
    uk: 'Завершено',
    es: 'Completado',
    it: 'Completato',
    zh: '已完成',
  },
  'order.statusCancelled': {
    tr: 'İptal Edildi',
    en: 'Cancelled',
    de: 'Storniert',
    ru: 'Отменено',
    ar: 'ملغى',
    fr: 'Annulée',
    fa: 'لغو شد',
    uk: 'Скасовано',
    es: 'Cancelado',
    it: 'Annullato',
    zh: '已取消',
  },
  'form.hide': {
    tr: 'Gizle',
    en: 'Hide',
    de: 'Ausblenden',
    ru: 'Скрыть',
    ar: 'إخفاء',
    fr: 'Masquer',
    fa: 'پنهان کردن',
    uk: 'Приховати',
    es: 'Ocultar',
    it: 'Nascondi',
    zh: '隐藏',
  },
  'landing.goToMenu': {
    tr: 'Menüye Git',
    en: 'View Menu',
    de: 'Zum Menü',
    ru: 'Перейти к меню',
    ar: 'عرض القائمة',
    fr: 'Voir le menu',
    fa: 'مشاهده منو',
    uk: 'Переглянути меню',
    es: 'Ver menú',
    it: 'Vai al menu',
    zh: '查看菜单',
  },
  'landing.wifi': {
    tr: 'Wi-Fi',
    en: 'Wi-Fi',
    de: 'WLAN',
    ru: 'Wi-Fi',
    ar: 'واي فاي',
    fr: 'Wi-Fi',
    fa: 'وای‌فای',
    uk: 'Wi-Fi',
    es: 'Wi-Fi',
    it: 'Wi-Fi',
    zh: 'Wi-Fi',
  },
  'landing.wifiPassword': {
    tr: 'Şifre: {password}',
    en: 'Password: {password}',
    de: 'Passwort: {password}',
    ru: 'Пароль: {password}',
    ar: 'كلمة المرور: {password}',
    fr: 'Mot de passe : {password}',
    fa: 'رمز عبور: {password}',
    uk: 'Пароль: {password}',
    es: 'Contraseña: {password}',
    it: 'Password: {password}',
    zh: '密码：{password}',
  },
  'landing.copied': {
    tr: 'Kopyalandı',
    en: 'Copied',
    de: 'Kopiert',
    ru: 'Скопировано',
    ar: 'تم النسخ',
    fr: 'Copié',
    fa: 'کپی شد',
    uk: 'Скопійовано',
    es: 'Copiado',
    it: 'Copiato',
    zh: '已复制',
  },
  'landing.copyPassword': {
    tr: 'Şifreyi kopyala',
    en: 'Copy password',
    de: 'Passwort kopieren',
    ru: 'Скопировать пароль',
    ar: 'نسخ كلمة المرور',
    fr: 'Copier le mot de passe',
    fa: 'کپی رمز عبور',
    uk: 'Скопіювати пароль',
    es: 'Copiar contraseña',
    it: 'Copia password',
    zh: '复制密码',
  },
  'landing.directions': {
    tr: 'Yol tarifi al',
    en: 'Get directions',
    de: 'Route anzeigen',
    ru: 'Проложить маршрут',
    ar: 'الحصول على الاتجاهات',
    fr: "Obtenir l'itinéraire",
    fa: 'مسیریابی',
    uk: 'Прокласти маршрут',
    es: 'Cómo llegar',
    it: 'Ottieni indicazioni',
    zh: '获取路线',
  },
  'allergen.name.gluten': {
    tr: 'Gluten',
    en: 'Gluten',
    de: 'Gluten',
    ru: 'Глютен',
    ar: 'الغلوتين',
    fr: 'Gluten',
    fa: 'گلوتن',
    uk: 'Глютен',
    es: 'Gluten',
    it: 'Glutine',
    zh: '麸质',
  },
  'allergen.name.crustaceans': {
    tr: 'Kabuklular',
    en: 'Crustaceans',
    de: 'Krebstiere',
    ru: 'Ракообразные',
    ar: 'القشريات',
    fr: 'Crustacés',
    fa: 'سخت‌پوستان',
    uk: 'Ракоподібні',
    es: 'Crustáceos',
    it: 'Crostacei',
    zh: '甲壳类',
  },
  'allergen.name.egg': {
    tr: 'Yumurta',
    en: 'Egg',
    de: 'Ei',
    ru: 'Яйца',
    ar: 'البيض',
    fr: 'Œuf',
    fa: 'تخم‌مرغ',
    uk: 'Яйця',
    es: 'Huevo',
    it: 'Uova',
    zh: '鸡蛋',
  },
  'allergen.name.fish': {
    tr: 'Balık',
    en: 'Fish',
    de: 'Fisch',
    ru: 'Рыба',
    ar: 'السمك',
    fr: 'Poisson',
    fa: 'ماهی',
    uk: 'Риба',
    es: 'Pescado',
    it: 'Pesce',
    zh: '鱼类',
  },
  'allergen.name.peanut': {
    tr: 'Yer Fıstığı',
    en: 'Peanut',
    de: 'Erdnuss',
    ru: 'Арахис',
    ar: 'الفول السوداني',
    fr: "Arachide",
    fa: 'بادام‌زمینی',
    uk: 'Арахіс',
    es: 'Cacahuete',
    it: "Arachidi",
    zh: '花生',
  },
  'allergen.name.soy': {
    tr: 'Soya',
    en: 'Soy',
    de: 'Soja',
    ru: 'Соя',
    ar: 'الصويا',
    fr: 'Soja',
    fa: 'سویا',
    uk: 'Соя',
    es: 'Soja',
    it: 'Soia',
    zh: '大豆',
  },
  'allergen.name.milk': {
    tr: 'Süt',
    en: 'Milk',
    de: 'Milch',
    ru: 'Молоко',
    ar: 'الحليب',
    fr: 'Lait',
    fa: 'شیر',
    uk: 'Молоко',
    es: 'Leche',
    it: 'Latte',
    zh: '牛奶',
  },
  'allergen.name.nuts': {
    tr: 'Sert Kabuklu Yemişler',
    en: 'Tree Nuts',
    de: 'Schalenfrüchte',
    ru: 'Орехи',
    ar: 'المكسرات',
    fr: 'Fruits à coque',
    fa: 'آجیل',
    uk: 'Горіхи',
    es: 'Frutos de cáscara',
    it: 'Frutta a guscio',
    zh: '坚果',
  },
  'allergen.name.celery': {
    tr: 'Kereviz',
    en: 'Celery',
    de: 'Sellerie',
    ru: 'Сельдерей',
    ar: 'الكرفس',
    fr: 'Céleri',
    fa: 'کرفس',
    uk: 'Селера',
    es: 'Apio',
    it: 'Sedano',
    zh: '芹菜',
  },
  'allergen.name.mustard': {
    tr: 'Hardal',
    en: 'Mustard',
    de: 'Senf',
    ru: 'Горчица',
    ar: 'الخردل',
    fr: 'Moutarde',
    fa: 'خردل',
    uk: 'Гірчиця',
    es: 'Mostaza',
    it: 'Senape',
    zh: '芥末',
  },
  'allergen.name.sesame': {
    tr: 'Susam',
    en: 'Sesame',
    de: 'Sesam',
    ru: 'Кунжут',
    ar: 'السمسم',
    fr: 'Sésame',
    fa: 'کنجد',
    uk: 'Кунжут',
    es: 'Sésamo',
    it: 'Sesamo',
    zh: '芝麻',
  },
  'allergen.name.sulphites': {
    tr: 'Sülfit',
    en: 'Sulphites',
    de: 'Sulfite',
    ru: 'Сульфиты',
    ar: 'الكبريتات',
    fr: 'Sulfites',
    fa: 'سولفیت',
    uk: 'Сульфіти',
    es: 'Sulfitos',
    it: 'Solfiti',
    zh: '亚硫酸盐',
  },
  'allergen.name.lupin': {
    tr: 'Acı Bakla',
    en: 'Lupin',
    de: 'Lupinen',
    ru: 'Люпин',
    ar: 'الترمس',
    fr: 'Lupin',
    fa: 'لوپین',
    uk: 'Люпин',
    es: 'Altramuz',
    it: 'Lupini',
    zh: '羽扇豆',
  },
  'allergen.name.molluscs': {
    tr: 'Yumuşakçalar',
    en: 'Molluscs',
    de: 'Weichtiere',
    ru: 'Моллюски',
    ar: 'الرخويات',
    fr: 'Mollusques',
    fa: 'نرم‌تنان',
    uk: 'Молюски',
    es: 'Moluscos',
    it: 'Molluschi',
    zh: '软体动物',
  },
} satisfies Record<string, Record<UILang, string>>

export type UIKey = keyof typeof UI_TEXT
